apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: ocm-with-helm
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/open-component-model/helm-test
  version:
    semver: 1.0.3
  repository:
    url: ghcr.io/skarlso/helm-test
    secretRef:
      name: creds
