apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: fluxdeployer-podinfo-configured
  namespace: ocm-system
spec:
  interval: 1m0s
  sourceRef:
    kind: Configuration
    name: ocm-with-helm-configured
  helmReleaseTemplate:
    interval: 5m

