apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend-release
  namespace: ocm-system
spec:
  interval: 5m
  chart:
    spec:
      chart: backend-chart
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
