apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: ocm-with-helm-localized
  namespace: ocm-system
spec:
  interval: 1m
  sourceRef:
    kind: Resource
    name: resource-pipeline-backend
  configRef:
    kind: ComponentVersion
    name: podinfo-pipeline
    resourceRef:
      name: config
      version: 1.0.0
